Name: product.rpc
ListenOn: 0.0.0.0:9001
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc


Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3307)/mall?charset=utf8mb4&parseTime=true

CacheRedis:
  - Host: 127.0.0.1:6379
    Type: node
#    Pass: