// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateRequst struct {
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  uint64 `json:"stock"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type CreateResponse struct {
	Id uint64 `json:"id"`
}

type DetailRequest struct {
	Id uint64 `json:"id"`
}

type DetailResponse struct {
	Id     uint64 `json:"id"`
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  uint64 `json:"stock"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type RemoveRequest struct {
	Id uint64 `json:"id"`
}

type RemoveResponse struct {
}

type UpdateRequest struct {
	Id     uint64 `json:"id"`
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  uint64 `json:"stock"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type UpdateResponse struct {
}
