// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire uint64 `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Gender   uint64 `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Id     uint64 `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}

type UserInfoResponse struct {
	Id     uint64 `json:"id"`
	Name   string `json:"name"`
	Gender uint64 `json:"gender"`
	Mobile string `json:"mobile"`
}
